name: Practice Workflow

on:
  push:
  schedule:
    - cron: '*/30 * * * *'  # Runs every day at midnight

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello
              run: echo "Hello, World!"